### ISSUE TITLE
Deprecated selectors

### ISSUE THREAD

**Issue by gottlike** [Kikobeats/afterglow-monokai-syntax#1]
![screenshot](https://cloud.githubusercontent.com/assets/278766/6587474/f572296e-c784-11e4-9229-480ff3c84019.png)

**Comment by Kikobeats** [comment]
Can you make a PR with the update?

**Comment by gottlike** [comment]
You closed the pull request, but didn't merge? Did you forget or do you want to check the code locally first?

**Comment by Kikobeats** [comment]
oh, I meged the code, this is a normal issue.

I publish a new version in atom package manager as `1.3.0`. Check now :-)

**Comment by gottlike** [comment]
I installed the new one, but the code is still the same, getting deprecation warnings. Also check the file in this repo: https://github.com/Kikobeats/afterglow-monokai-syntax/blob/master/stylesheets/base.less#L3

I think something went wrong when merging..

**Comment by gottlike** [comment]
Maybe because I deleted the repo in the meantime. I will create a new pull request..

**Comment by Kikobeats** [comment]
hmm is true, is not in the history of the git repository... please create again and I will merge it

**Comment by Kikobeats** [comment]
@gottlike can you try now?

**Comment by gottlike** [comment]
Installed 1.3.2 and it's in now :thumbsup: :)

**Comment by Kikobeats** [comment]
yeah!

I hate the system of version of apm, is very confuse...

thanks man!
